# Qwen3-VL-8B-Instruct LoRA fine-tuning config for VERIFIER
# Task: ACCEPT/REJECT classification for mask group verification
# Based on plans.md v0 verifier training
#
# Usage:
#   1. Create verifier dataset: python scripts/custom/create_verifier_dataset.py
#   2. Train: PYTHONPATH=. accelerate launch -m axolotl.cli.train examples/qwen3-vl/verifier-lora-8b.yaml

base_model: Qwen/Qwen3-VL-8B-Instruct
processor_type: AutoProcessor

# Required for vision chat templates with images
skip_prepare_dataset: true
remove_unused_columns: false
sample_packing: false

# Qwen3-VL uses the same chat template format as Qwen2-VL
chat_template: qwen2_vl

datasets:
  # Verifier dataset with ACCEPT/REJECT labels
  # Created by scripts/custom/create_verifier_dataset.py
  - path: ./data/verifier-dataset/train.json
    type: chat_template
    ds_type: json

dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir: ./outputs/qwen3-vl-verifier-accept-reject

adapter: lora
lora_model_dir:

# Following plans.md: Max text length 256 (short ACCEPT/REJECT responses)
sequence_len: 256
pad_to_sequence_len: false

# LoRA config (following plans.md recommendations)
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
# Target attention + MLP layers for Qwen3-VL
lora_target_modules: 'model.language_model.layers.[\d]+.(mlp|cross_attn|self_attn).(up|down|gate|q|k|v|o)_proj'

# Weights & Biases logging
wandb_project: qwen3-vl-verifier
wandb_entity:
wandb_watch: false  # Disable gradient logging (too noisy)
wandb_name: verifier-lora-8b-v0
wandb_log_model: checkpoint

# Custom plugin for image logging
plugins:
  - scripts.custom.wandb_image_callback.WandbImagePlugin

# Training config (from plans.md)
# Effective batch size: 64 (micro_batch * grad_accum * num_gpus)
gradient_accumulation_steps: 16
micro_batch_size: 4
num_epochs: 1  # v0: 1 epoch first
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0001  # 1e-4 as recommended for LoRA

bf16: true
fp16:
tf32: true

gradient_checkpointing: true
logging_steps: 10
flash_attention: true
eager_attention:

# Warmup 3% as per plans.md
warmup_ratio: 0.03
evals_per_epoch: 4
saves_per_epoch: 2
weight_decay: 0.0

# Evaluation metrics for classification
# Track: Accuracy, Precision at high-confidence ACCEPT
eval_causal_lm_metrics:
  - accuracy

